### ISSUE TITLE
NameError: name 'n_threads' is not defined

### ISSUE THREAD

**Issue by leonardltk** [furkanyesiler/acoss#21]
Hi, I git cloned this on 9th April 2020.

I was running
```python
batch_feature_extractor(dataset_csv=COVERS_80_CSV, 
                        audio_dir=audio_dir, 
                        feature_dir=feature_dir,
                        n_workers=4,
                        mode="parallel", 
                        params=extractor_profile)
```

And the following error was returned
```python
Traceback (most recent call last):
  File "./debug.py", line 56, in <module>
    batch_feature_extractor(dataset_csv=COVERS_80_CSV,
  File "/data3/lootiangkuan/AudioHashing/QbH/acoss/acoss/extractors.py", line 150, in batch_feature_extractor
    Parallel(n_jobs=n_threads, verbose=1)(delayed(compute_features_from_list_file)\
NameError: name 'n_threads' is not defined
```

**Comment by leonardltk** [comment]
You probably need to replace `n_jobs=n_threads` with `n_jobs=n_workers` [here](https://github.com/furkanyesiler/acoss/blob/master/acoss/extractors.py/#L150)

**Comment by albincorreya** [comment]
@leonardltk Thanks for reporting the issue. It should be solved by now.
