### ISSUE TITLE
UnboundLocalError: local variable 'progressbar' referenced before assignment

### ISSUE THREAD

**Issue by leonardltk** [furkanyesiler/acoss#22]
Hi, i am trying to run the benchmark.

```python
benchmark(dataset_csv=COVERS_80_CSV, 
    feature_dir=feature_dir,
    algorithm="Serra09", 
    parallel=True,
    n_workers=2)
```

This error is given.
```python
Traceback (most recent call last):
  File "/data3/lootiangkuan/AudioHashing/QbH/acoss/acoss/coverid.py", line 65, in benchmark
    serra09.all_pairwise(parallel, n_cores=n_workers, symmetric=True)
  File "/data3/lootiangkuan/AudioHashing/QbH/acoss/acoss/algorithms/algorithm_template.py", line 191, in all_pairwise
    progressbar.next()
UnboundLocalError: local variable 'progressbar' referenced before assignment
```

**Comment by albincorreya** [comment]
@leonardltk Thanks for reporting the issue. It should be solved by now.
